/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

/**
 *
 * @author Romi
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Menu = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu7 = new javax.swing.JMenu();
        jMenu8 = new javax.swing.JMenu();
        jMenu9 = new javax.swing.JMenu();
        jMenu10 = new javax.swing.JMenu();
        jMenu11 = new javax.swing.JMenu();
        jMenu12 = new javax.swing.JMenu();
        jMenu13 = new javax.swing.JMenu();
        jMenu14 = new javax.swing.JMenu();
        jMenu15 = new javax.swing.JMenu();
        jMenu16 = new javax.swing.JMenu();
        jMenu17 = new javax.swing.JMenu();
        jMenu18 = new javax.swing.JMenu();
        jMenu19 = new javax.swing.JMenu();
        jMenu20 = new javax.swing.JMenu();
        jMenu21 = new javax.swing.JMenu();
        jMenu22 = new javax.swing.JMenu();
        jMenu23 = new javax.swing.JMenu();
        jMenu24 = new javax.swing.JMenu();
        jMenu25 = new javax.swing.JMenu();
        jMenu26 = new javax.swing.JMenu();
        jMenu27 = new javax.swing.JMenu();
        jMenu28 = new javax.swing.JMenu();
        jMenu29 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();
        jMenu6 = new javax.swing.JMenu();
        jMenu30 = new javax.swing.JMenu();
        jMenu31 = new javax.swing.JMenu();
        jMenu32 = new javax.swing.JMenu();
        jMenu33 = new javax.swing.JMenu();
        jMenu34 = new javax.swing.JMenu();
        jMenu36 = new javax.swing.JMenu();
        jMenu37 = new javax.swing.JMenu();
        jMenu38 = new javax.swing.JMenu();
        jMenu39 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout MenuLayout = new javax.swing.GroupLayout(Menu);
        Menu.setLayout(MenuLayout);
        MenuLayout.setHorizontalGroup(
            MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 604, Short.MAX_VALUE)
        );
        MenuLayout.setVerticalGroup(
            MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 473, Short.MAX_VALUE)
        );

        jMenu1.setText("Torneo");

        jMenu7.setText("Agregar");
        jMenu7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu7MouseClicked(evt);
            }
        });
        jMenu7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu7ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenu7);

        jMenu8.setText("Modificar");
        jMenu8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu8MouseClicked(evt);
            }
        });
        jMenu1.add(jMenu8);

        jMenu9.setText("Baja/Alta");
        jMenu9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu9MouseClicked(evt);
            }
        });
        jMenu1.add(jMenu9);

        jMenuBar1.add(jMenu1);

        jMenu10.setText("Estadio");

        jMenu11.setText("Agregar");
        jMenu11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu11MouseClicked(evt);
            }
        });
        jMenu10.add(jMenu11);

        jMenu12.setText("Modificar");
        jMenu12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu12MouseClicked(evt);
            }
        });
        jMenu10.add(jMenu12);

        jMenu13.setText("Baja/Alta");
        jMenu13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu13MouseClicked(evt);
            }
        });
        jMenu10.add(jMenu13);

        jMenuBar1.add(jMenu10);

        jMenu14.setText("Jugador");

        jMenu15.setText("Agregar");
        jMenu15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu15MouseClicked(evt);
            }
        });
        jMenu14.add(jMenu15);

        jMenu16.setText("Modificar");
        jMenu16.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu16MouseClicked(evt);
            }
        });
        jMenu14.add(jMenu16);

        jMenu17.setText("Baja/Alta");
        jMenu17.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu17MouseClicked(evt);
            }
        });
        jMenu14.add(jMenu17);

        jMenuBar1.add(jMenu14);

        jMenu18.setText("Sponsor");

        jMenu19.setText("Agregar");
        jMenu19.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu19MouseClicked(evt);
            }
        });
        jMenu18.add(jMenu19);

        jMenu20.setText("Modificar");
        jMenu20.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu20MouseClicked(evt);
            }
        });
        jMenu18.add(jMenu20);

        jMenu21.setText("Baja/Alta");
        jMenu21.setToolTipText("");
        jMenu21.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu21MouseClicked(evt);
            }
        });
        jMenu18.add(jMenu21);

        jMenuBar1.add(jMenu18);

        jMenu22.setText("Patrocinio");

        jMenu23.setText("Agregar");
        jMenu23.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu23MouseClicked(evt);
            }
        });
        jMenu22.add(jMenu23);

        jMenu24.setText("Modificar");
        jMenu24.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu24MouseClicked(evt);
            }
        });
        jMenu22.add(jMenu24);

        jMenu25.setText("Baja/Alta");
        jMenu25.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu25MouseClicked(evt);
            }
        });
        jMenu22.add(jMenu25);

        jMenuBar1.add(jMenu22);

        jMenu26.setText("Encuentro");

        jMenu27.setText("Agregar");
        jMenu27.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu27MouseClicked(evt);
            }
        });
        jMenu26.add(jMenu27);

        jMenu28.setText("Modificar");
        jMenu28.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu28MouseClicked(evt);
            }
        });
        jMenu26.add(jMenu28);

        jMenu29.setText("Baja/Alta");
        jMenu29.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu29MouseClicked(evt);
            }
        });
        jMenu26.add(jMenu29);

        jMenuBar1.add(jMenu26);

        jMenu2.setText("Listar");
        jMenu2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu2MouseClicked(evt);
            }
        });
        jMenu2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu2ActionPerformed(evt);
            }
        });

        jMenu3.setText("Jugador");
        jMenu3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu3MouseClicked(evt);
            }
        });
        jMenu2.add(jMenu3);

        jMenu4.setText("Sponsor");
        jMenu4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu4MouseClicked(evt);
            }
        });
        jMenu2.add(jMenu4);

        jMenu5.setText("Encuentro");
        jMenu5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu5MouseClicked(evt);
            }
        });
        jMenu2.add(jMenu5);

        jMenu6.setText("Estadio");
        jMenu6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu6MouseClicked(evt);
            }
        });
        jMenu2.add(jMenu6);

        jMenu30.setText("Patrocinio");
        jMenu30.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu30MouseClicked(evt);
            }
        });
        jMenu2.add(jMenu30);

        jMenu31.setText("Torneo");
        jMenu31.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu31MouseClicked(evt);
            }
        });
        jMenu2.add(jMenu31);

        jMenuBar1.add(jMenu2);

        jMenu32.setText("Busquedas");
        jMenu32.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu32MouseClicked(evt);
            }
        });

        jMenu33.setText("Buscar Sponsor por Jugador");
        jMenu33.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu33MouseClicked(evt);
            }
        });
        jMenu32.add(jMenu33);

        jMenu34.setText("Buscar Jugadores de un sponsor");
        jMenu34.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu34MouseClicked(evt);
            }
        });
        jMenu32.add(jMenu34);

        jMenu36.setText("Buscar Encuentros Por Fecha");
        jMenu36.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu36MouseClicked(evt);
            }
        });
        jMenu32.add(jMenu36);

        jMenu37.setText("Listar Jugadores Por Puntaje");
        jMenu37.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu37MouseClicked(evt);
            }
        });
        jMenu32.add(jMenu37);

        jMenu38.setText("Listar Torneos Por Jugador");
        jMenu38.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu38MouseClicked(evt);
            }
        });
        jMenu32.add(jMenu38);

        jMenu39.setText("Listar Encuentros Proximos");
        jMenu39.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu39MouseClicked(evt);
            }
        });
        jMenu32.add(jMenu39);

        jMenuBar1.add(jMenu32);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Menu)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Menu)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenu7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu7MouseClicked
        Menu.removeAll();
        Menu.repaint();
        frmiAgregarTorneo aC=new frmiAgregarTorneo();
        aC.setVisible(true);
        Menu.add(aC);
        Menu.moveToFront(aC);
    }//GEN-LAST:event_jMenu7MouseClicked

    private void jMenu7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu7ActionPerformed

    }//GEN-LAST:event_jMenu7ActionPerformed

    private void jMenu8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu8MouseClicked
        Menu.removeAll();
        Menu.repaint();
        frmiModificarTorneo aC=new frmiModificarTorneo();
        aC.setVisible(true);
        Menu.add(aC);
        Menu.moveToFront(aC);
    }//GEN-LAST:event_jMenu8MouseClicked

    private void jMenu9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu9MouseClicked
        Menu.removeAll();
        Menu.repaint();
        frmiEliminarTorneo aC=new frmiEliminarTorneo();
        aC.setVisible(true);
        Menu.add(aC);
        Menu.moveToFront(aC);        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu9MouseClicked

    private void jMenu11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu11MouseClicked
         Menu.removeAll();
        Menu.repaint();
        frmiAgregarEstadio aC=new frmiAgregarEstadio();
        aC.setVisible(true);
        Menu.add(aC);
        Menu.moveToFront(aC);
    }//GEN-LAST:event_jMenu11MouseClicked

    private void jMenu12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu12MouseClicked
        Menu.removeAll();
        Menu.repaint();
        frmiModificarEstadio aC=new frmiModificarEstadio();
        aC.setVisible(true);
        Menu.add(aC);
        Menu.moveToFront(aC);
    }//GEN-LAST:event_jMenu12MouseClicked

    private void jMenu13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu13MouseClicked
        Menu.removeAll();
        Menu.repaint();
        frmiEliminarEstadio aC=new frmiEliminarEstadio();
        aC.setVisible(true);
        Menu.add(aC);
        Menu.moveToFront(aC);          // TODO add your handling code here:
    }//GEN-LAST:event_jMenu13MouseClicked

    private void jMenu15MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu15MouseClicked
         Menu.removeAll();
        Menu.repaint();
        frmiAgregarJugador aC=new frmiAgregarJugador();
        aC.setVisible(true);
        Menu.add(aC);
        Menu.moveToFront(aC);        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu15MouseClicked

    private void jMenu16MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu16MouseClicked
        Menu.removeAll();
        Menu.repaint();
        frmiModificarJugador aC=new frmiModificarJugador();
        aC.setVisible(true);
        Menu.add(aC);
        Menu.moveToFront(aC);        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu16MouseClicked

    private void jMenu17MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu17MouseClicked
       Menu.removeAll();
        Menu.repaint();
        frmiEliminarJugador aC=new frmiEliminarJugador();
        aC.setVisible(true);
        Menu.add(aC);
        Menu.moveToFront(aC);
    }//GEN-LAST:event_jMenu17MouseClicked

    private void jMenu19MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu19MouseClicked
        Menu.removeAll();
        Menu.repaint();
        frmiAgregarSponsor aC=new frmiAgregarSponsor();
        aC.setVisible(true);
        Menu.add(aC);
        Menu.moveToFront(aC);        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu19MouseClicked

    private void jMenu20MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu20MouseClicked
        Menu.removeAll();
        Menu.repaint();
        frmiModificarSponsor aC=new frmiModificarSponsor();
        aC.setVisible(true);
        Menu.add(aC);
        Menu.moveToFront(aC);         // TODO add your handling code here:
    }//GEN-LAST:event_jMenu20MouseClicked

    private void jMenu21MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu21MouseClicked
        Menu.removeAll();
        Menu.repaint();
        frmiEliminarSponsor aC=new frmiEliminarSponsor();
        aC.setVisible(true);
        Menu.add(aC);
        Menu.moveToFront(aC);          // TODO add your handling code here:
    }//GEN-LAST:event_jMenu21MouseClicked

    private void jMenu23MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu23MouseClicked
        Menu.removeAll();
        Menu.repaint();
        frmiAgregarPatrocinio aC=new frmiAgregarPatrocinio();
        aC.setVisible(true);
        Menu.add(aC);
        Menu.moveToFront(aC);      
    }//GEN-LAST:event_jMenu23MouseClicked

    private void jMenu24MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu24MouseClicked
        Menu.removeAll();
        Menu.repaint();
        frmiModificarPatrocinio aC=new frmiModificarPatrocinio();
        aC.setVisible(true);
        Menu.add(aC);
        Menu.moveToFront(aC); 
    }//GEN-LAST:event_jMenu24MouseClicked

    private void jMenu25MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu25MouseClicked
       Menu.removeAll();
        Menu.repaint();
        frmiEliminarPatrocinio aC=new frmiEliminarPatrocinio();
        aC.setVisible(true);
        Menu.add(aC);
        Menu.moveToFront(aC); 
    }//GEN-LAST:event_jMenu25MouseClicked

    private void jMenu27MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu27MouseClicked
        Menu.removeAll();
        Menu.repaint();
        frmiAgregarEncuentro aC=new frmiAgregarEncuentro();
        aC.setVisible(true);
        Menu.add(aC);
        Menu.moveToFront(aC);
    }//GEN-LAST:event_jMenu27MouseClicked

    private void jMenu28MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu28MouseClicked
        Menu.removeAll();
        Menu.repaint();
        frmiModificarEncuentro aC=new frmiModificarEncuentro();
        aC.setVisible(true);
        Menu.add(aC);
        Menu.moveToFront(aC);        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu28MouseClicked

    private void jMenu29MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu29MouseClicked
        Menu.removeAll();
        Menu.repaint();
        frmiEliminarEncuentro aC=new frmiEliminarEncuentro();
        aC.setVisible(true);
        Menu.add(aC);
        Menu.moveToFront(aC);
    }//GEN-LAST:event_jMenu29MouseClicked

    private void jMenu2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu2ActionPerformed
        
    }//GEN-LAST:event_jMenu2ActionPerformed

    private void jMenu2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu2MouseClicked
        
    }//GEN-LAST:event_jMenu2MouseClicked

    private void jMenu31MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu31MouseClicked
       Menu.removeAll();
        Menu.repaint();
        frmiVerTorneos aC=new frmiVerTorneos();
        aC.setVisible(true);
        Menu.add(aC);
        Menu.moveToFront(aC);
    }//GEN-LAST:event_jMenu31MouseClicked

    private void jMenu4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu4MouseClicked
     Menu.removeAll();
        Menu.repaint();
        frmiVerSponsors aC=new frmiVerSponsors();
        aC.setVisible(true);
        Menu.add(aC);
        Menu.moveToFront(aC);
    }//GEN-LAST:event_jMenu4MouseClicked

    private void jMenu5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu5MouseClicked
         Menu.removeAll();
        Menu.repaint();
        frmiVerEncuentros aC=new frmiVerEncuentros();
        aC.setVisible(true);
        Menu.add(aC);
        Menu.moveToFront(aC);
    }//GEN-LAST:event_jMenu5MouseClicked

    private void jMenu6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu6MouseClicked
          Menu.removeAll();
        Menu.repaint();
        frmiVerEstadios aC=new frmiVerEstadios();
        aC.setVisible(true);
        Menu.add(aC);
        Menu.moveToFront(aC);
    }//GEN-LAST:event_jMenu6MouseClicked

    private void jMenu3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu3MouseClicked
         Menu.removeAll();
        Menu.repaint();
        frmiVerJugadores aC=new frmiVerJugadores();
        aC.setVisible(true);
        Menu.add(aC);
        Menu.moveToFront(aC);
    }//GEN-LAST:event_jMenu3MouseClicked

    private void jMenu30MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu30MouseClicked
       Menu.removeAll();
        Menu.repaint();
        frmiVerPatrocinios aC=new frmiVerPatrocinios();
        aC.setVisible(true);
        Menu.add(aC);
        Menu.moveToFront(aC);
    }//GEN-LAST:event_jMenu30MouseClicked

    private void jMenu33MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu33MouseClicked
        Menu.removeAll();
        Menu.repaint();
        frmiBuscarSponsorxJugador aC=new frmiBuscarSponsorxJugador();
        aC.setVisible(true);
        Menu.add(aC);
        Menu.moveToFront(aC);
    }//GEN-LAST:event_jMenu33MouseClicked

    private void jMenu34MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu34MouseClicked
       
        Menu.removeAll();
        Menu.repaint();
        frmiBuscaJugadoresdeunSponsor aC=new frmiBuscaJugadoresdeunSponsor();
        aC.setVisible(true);
        Menu.add(aC);
        Menu.moveToFront(aC);
    }//GEN-LAST:event_jMenu34MouseClicked

    private void jMenu36MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu36MouseClicked
     Menu.removeAll();
        Menu.repaint();
        frmiBuscarEncuentrosPorFecha aC=new frmiBuscarEncuentrosPorFecha();
        aC.setVisible(true);
        Menu.add(aC);
        Menu.moveToFront(aC);
    }//GEN-LAST:event_jMenu36MouseClicked

    private void jMenu37MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu37MouseClicked
        Menu.removeAll();
        Menu.repaint();
        frmiListarJugadoresPorPuntaje aC=new frmiListarJugadoresPorPuntaje();
        aC.setVisible(true);
        Menu.add(aC);
        Menu.moveToFront(aC);
    }//GEN-LAST:event_jMenu37MouseClicked

    private void jMenu38MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu38MouseClicked
     Menu.removeAll();
        Menu.repaint();
        frmiListarTorneosPorJugador aC=new frmiListarTorneosPorJugador();
        aC.setVisible(true);
        Menu.add(aC);
        Menu.moveToFront(aC);
    }//GEN-LAST:event_jMenu38MouseClicked

    private void jMenu39MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu39MouseClicked
             Menu.removeAll();
        Menu.repaint();
        frmiListarEncuentrosProximos aC=new frmiListarEncuentrosProximos();
        aC.setVisible(true);
        Menu.add(aC);
        Menu.moveToFront(aC);
    }//GEN-LAST:event_jMenu39MouseClicked

    private void jMenu32MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu32MouseClicked
     
    }//GEN-LAST:event_jMenu32MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane Menu;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu10;
    private javax.swing.JMenu jMenu11;
    private javax.swing.JMenu jMenu12;
    private javax.swing.JMenu jMenu13;
    private javax.swing.JMenu jMenu14;
    private javax.swing.JMenu jMenu15;
    private javax.swing.JMenu jMenu16;
    private javax.swing.JMenu jMenu17;
    private javax.swing.JMenu jMenu18;
    private javax.swing.JMenu jMenu19;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu20;
    private javax.swing.JMenu jMenu21;
    private javax.swing.JMenu jMenu22;
    private javax.swing.JMenu jMenu23;
    private javax.swing.JMenu jMenu24;
    private javax.swing.JMenu jMenu25;
    private javax.swing.JMenu jMenu26;
    private javax.swing.JMenu jMenu27;
    private javax.swing.JMenu jMenu28;
    private javax.swing.JMenu jMenu29;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu30;
    private javax.swing.JMenu jMenu31;
    private javax.swing.JMenu jMenu32;
    private javax.swing.JMenu jMenu33;
    private javax.swing.JMenu jMenu34;
    private javax.swing.JMenu jMenu36;
    private javax.swing.JMenu jMenu37;
    private javax.swing.JMenu jMenu38;
    private javax.swing.JMenu jMenu39;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenu jMenu9;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables
}
